name: Main

on:
  push:
    branches: [ main ]
    tags:
      - v[0-9]*
  pull_request:
    branches: [ main ]

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
      - uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@v2
      - name: Lint code
        run: cargo clippy --all-targets -- -D clippy::all

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - name: Build
        run: cargo check --all

  unit-test:
    needs: [codestyle, lint, compile]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.59.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cargo test --workspace
